# Default mode configuration


name: "default"
description: "Default running mode"
test_mode: false
debug: false
verbose: true

# Runtime settings
selected_model: "data_preprocessor"  # choose the module to run
validate_after_steps: 100
save_checkpoint_steps: 500

# WLASL specific settings
find_missing: false  # whether to only detect missing files 